# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - run: npm install @stuntman/server@latest @stuntman/client@latest
