name: Continous integration

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install stuff
        shell: bash
        run: |
          npm install @stuntman/server@latest @stuntman/client@latest
